<a href="https://colab.research.google.com/github/hemanth714444/2203A52192-lab-1-deep-learning/blob/main/2203A52192_ipnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

Y_actual = np.array([20, 30, 40, 50, 60])
Y_pred = np.array([20.5, 30.3, 40.25, 50.66, 60.7])

def calculate_metrics(y_true, y_pred):
    n = len(y_true)
    abs_errors = np.abs(y_true - y_pred)
    squared_errors = (y_true - y_pred) ** 2
    mae = np.sum(abs_errors) / n
    mse = np.sum(squared_errors) / n
    rmse = np.sqrt(mse)
    return mae, mse, rmse

manual_mae, manual_mse, manual_rmse = calculate_metrics(Y_actual, Y_pred)


lib_mae = mean_absolute_error(Y_actual, Y_pred)
lib_mse = mean_squared_error(Y_actual, Y_pred)
lib_rmse = np.sqrt(lib_mse)


print("Manual Calculations:")
print(f"MAE: {manual_mae:.4f}, MSE: {manual_mse:.4f}, RMSE: {manual_rmse:.4f}")

print("\nLibrary Results:")
print(f"MAE: {lib_mae:.4f}, MSE: {lib_mse:.4f}, RMSE: {lib_rmse:.4f}")


Manual Calculations:
MAE: 0.4820, MSE: 0.2656, RMSE: 0.5154

Library Results:
MAE: 0.4820, MSE: 0.2656, RMSE: 0.5154


In [2]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
y_pred = [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]


cm = confusion_matrix(y_actual, y_pred)
print("Confusion Matrix:")
print(cm)


accuracy = accuracy_score(y_actual, y_pred)
print("\nAccuracy:", accuracy)


precision = precision_score(y_actual, y_pred, average=None)
recall = recall_score(y_actual, y_pred, average=None)
f1 = f1_score(y_actual, y_pred, average=None)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

precision_overall = precision_score(y_actual, y_pred, average='macro')
recall_overall = recall_score(y_actual, y_pred, average='macro')
f1_overall = f1_score(y_actual, y_pred, average='macro')

print("\nOverall Precision (Macro):", precision_overall)
print("Overall Recall (Macro):", recall_overall)
print("Overall F1 Score (Macro):", f1_overall)

Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]

Accuracy: 0.3333333333333333
Precision: [0.33333333 0.33333333 0.33333333]
Recall: [0.4 0.2 0.4]
F1 Score: [0.36363636 0.25       0.36363636]

Overall Precision (Macro): 0.3333333333333333
Overall Recall (Macro): 0.3333333333333333
Overall F1 Score (Macro): 0.32575757575757575
