<a href="https://colab.research.google.com/github/hemanth714444/2203A52192-lab-1-deep-learning/blob/main/2203A52192_ipnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

y_actual = np.array([20, 30, 40, 50, 60])
y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

mae=np.mean(np.abs(y_actual - y_pred))
mse=np.mean((y_actual - y_pred)**2)
rmse=np.sqrt(mse)
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Absolute Error: 0.4600000000000016
Mean Squared Error: 0.24600000000000147
Root Mean Squared Error: 0.49598387070549127
Mean Absolute Error: 0.4600000000000016
Mean Squared Error: 0.24600000000000147
Root Mean Squared Error: 0.49598387070549127


In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Data from Table 2
y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
y_pred = [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]

# Confusion Matrix
cm = confusion_matrix(y_actual, y_pred)
print("Confusion Matrix:")
print(cm)

# Accuracy
accuracy = accuracy_score(y_actual, y_pred)
print("\nAccuracy:", accuracy)

# Precision, Recall, F1 Score
precision = precision_score(y_actual, y_pred, average=None)
recall = recall_score(y_actual, y_pred, average=None)
f1 = f1_score(y_actual, y_pred, average=None)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# Overall metrics (micro, macro, weighted averages)
precision_overall = precision_score(y_actual, y_pred, average='macro')
recall_overall = recall_score(y_actual, y_pred, average='macro')
f1_overall = f1_score(y_actual, y_pred, average='macro')

print("\nOverall Precision (Macro):", precision_overall)
print("Overall Recall (Macro):", recall_overall)
print("Overall F1 Score (Macro):", f1_overall)

Confusion Matrix:
[[2 1 2]
 [2 1 2]
 [2 1 2]]

Accuracy: 0.3333333333333333
Precision: [0.33333333 0.33333333 0.33333333]
Recall: [0.4 0.2 0.4]
F1 Score: [0.36363636 0.25       0.36363636]

Overall Precision (Macro): 0.3333333333333333
Overall Recall (Macro): 0.3333333333333333
Overall F1 Score (Macro): 0.32575757575757575


In [10]:
y_actual = [20, 30, 40, 50, 60]
y_pred = [20.5, 30.3, 40.2, 50.6, 60.7]

n = len(y_actual)
mae = sum(abs(ya - yp) for ya, yp in zip(y_actual, y_pred)) / n
mse = sum((ya - yp) ** 2 for ya, yp in zip(y_actual, y_pred)) / n
rmse = mse ** 0.5

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)

Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127


In [11]:

y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
y_pred = [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]

# Initialize confusion matrix
classes = sorted(set(y_actual))  # Unique classes: [0, 1, 2]
confusion_matrix = {c: {c_: 0 for c_ in classes} for c in classes}

# Fill confusion matrix
for ya, yp in zip(y_actual, y_pred):
    confusion_matrix[ya][yp] += 1

# Metrics calculation
total_correct = sum(confusion_matrix[c][c] for c in classes)
total_samples = len(y_actual)

# Accuracy
accuracy = total_correct / total_samples

# Precision, Recall, F1 Score for each class
precision = {}
recall = {}
f1_score = {}

for c in classes:
    tp = confusion_matrix[c][c]
    fp = sum(confusion_matrix[c_][c] for c_ in classes if c_ != c)
    fn = sum(confusion_matrix[c][c_] for c_ in classes if c_ != c)
    precision[c] = tp / (tp + fp) if tp + fp > 0 else 0
    recall[c] = tp / (tp + fn) if tp + fn > 0 else 0
    f1_score[c] = (2 * precision[c] * recall[c] / (precision[c] + recall[c])) if precision[c] + recall[c] > 0 else 0

# Print results
print("Confusion Matrix:")
for c in classes:
    print(c, [confusion_matrix[c][c_] for c_ in classes])

print("\nAccuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)

Confusion Matrix:
0 [2, 1, 2]
1 [2, 1, 2]
2 [2, 1, 2]

Accuracy: 0.3333333333333333
Precision: {0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333}
Recall: {0: 0.4, 1: 0.2, 2: 0.4}
F1 Score: {0: 0.3636363636363636, 1: 0.25, 2: 0.3636363636363636}
